/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WorksIndexImport } from './routes/works/index'
import { Route as WorksProjectsZenzeroImport } from './routes/works/_projects/Zenzero'
import { Route as WorksProjectsVeneziaDresdenImport } from './routes/works/_projects/VeneziaDresden'
import { Route as WorksProjectsVectivImport } from './routes/works/_projects/Vectiv'
import { Route as WorksProjectsStazImport } from './routes/works/_projects/Staz'
import { Route as WorksProjectsRunForTheArcticImport } from './routes/works/_projects/RunForTheArctic'
import { Route as WorksProjectsOutdooraImport } from './routes/works/_projects/Outdoora'
import { Route as WorksProjectsEarthWeekImport } from './routes/works/_projects/EarthWeek'
import { Route as WorksProjectsCadoreDeliveryImport } from './routes/works/_projects/CadoreDelivery'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorksIndexRoute = WorksIndexImport.update({
  path: '/works/',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsZenzeroRoute = WorksProjectsZenzeroImport.update({
  path: '/works/Zenzero',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsVeneziaDresdenRoute =
  WorksProjectsVeneziaDresdenImport.update({
    path: '/works/VeneziaDresden',
    getParentRoute: () => rootRoute,
  } as any)

const WorksProjectsVectivRoute = WorksProjectsVectivImport.update({
  path: '/works/Vectiv',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsStazRoute = WorksProjectsStazImport.update({
  path: '/works/Staz',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsRunForTheArcticRoute =
  WorksProjectsRunForTheArcticImport.update({
    path: '/works/RunForTheArctic',
    getParentRoute: () => rootRoute,
  } as any)

const WorksProjectsOutdooraRoute = WorksProjectsOutdooraImport.update({
  path: '/works/Outdoora',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsEarthWeekRoute = WorksProjectsEarthWeekImport.update({
  path: '/works/EarthWeek',
  getParentRoute: () => rootRoute,
} as any)

const WorksProjectsCadoreDeliveryRoute =
  WorksProjectsCadoreDeliveryImport.update({
    path: '/works/CadoreDelivery',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksIndexImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/CadoreDelivery': {
      id: '/works/_projects/CadoreDelivery'
      path: '/works/CadoreDelivery'
      fullPath: '/works/CadoreDelivery'
      preLoaderRoute: typeof WorksProjectsCadoreDeliveryImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/EarthWeek': {
      id: '/works/_projects/EarthWeek'
      path: '/works/EarthWeek'
      fullPath: '/works/EarthWeek'
      preLoaderRoute: typeof WorksProjectsEarthWeekImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/Outdoora': {
      id: '/works/_projects/Outdoora'
      path: '/works/Outdoora'
      fullPath: '/works/Outdoora'
      preLoaderRoute: typeof WorksProjectsOutdooraImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/RunForTheArctic': {
      id: '/works/_projects/RunForTheArctic'
      path: '/works/RunForTheArctic'
      fullPath: '/works/RunForTheArctic'
      preLoaderRoute: typeof WorksProjectsRunForTheArcticImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/Staz': {
      id: '/works/_projects/Staz'
      path: '/works/Staz'
      fullPath: '/works/Staz'
      preLoaderRoute: typeof WorksProjectsStazImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/Vectiv': {
      id: '/works/_projects/Vectiv'
      path: '/works/Vectiv'
      fullPath: '/works/Vectiv'
      preLoaderRoute: typeof WorksProjectsVectivImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/VeneziaDresden': {
      id: '/works/_projects/VeneziaDresden'
      path: '/works/VeneziaDresden'
      fullPath: '/works/VeneziaDresden'
      preLoaderRoute: typeof WorksProjectsVeneziaDresdenImport
      parentRoute: typeof rootRoute
    }
    '/works/_projects/Zenzero': {
      id: '/works/_projects/Zenzero'
      path: '/works/Zenzero'
      fullPath: '/works/Zenzero'
      preLoaderRoute: typeof WorksProjectsZenzeroImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  ContactRoute,
  WorksIndexRoute,
  WorksProjectsCadoreDeliveryRoute,
  WorksProjectsEarthWeekRoute,
  WorksProjectsOutdooraRoute,
  WorksProjectsRunForTheArcticRoute,
  WorksProjectsStazRoute,
  WorksProjectsVectivRoute,
  WorksProjectsVeneziaDresdenRoute,
  WorksProjectsZenzeroRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/works/",
        "/works/_projects/CadoreDelivery",
        "/works/_projects/EarthWeek",
        "/works/_projects/Outdoora",
        "/works/_projects/RunForTheArctic",
        "/works/_projects/Staz",
        "/works/_projects/Vectiv",
        "/works/_projects/VeneziaDresden",
        "/works/_projects/Zenzero"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/contact": {
      "filePath": "contact.jsx"
    },
    "/works/": {
      "filePath": "works/index.jsx"
    },
    "/works/_projects/CadoreDelivery": {
      "filePath": "works/_projects/CadoreDelivery.jsx"
    },
    "/works/_projects/EarthWeek": {
      "filePath": "works/_projects/EarthWeek.jsx"
    },
    "/works/_projects/Outdoora": {
      "filePath": "works/_projects/Outdoora.jsx"
    },
    "/works/_projects/RunForTheArctic": {
      "filePath": "works/_projects/RunForTheArctic.jsx"
    },
    "/works/_projects/Staz": {
      "filePath": "works/_projects/Staz.jsx"
    },
    "/works/_projects/Vectiv": {
      "filePath": "works/_projects/Vectiv.jsx"
    },
    "/works/_projects/VeneziaDresden": {
      "filePath": "works/_projects/VeneziaDresden.jsx"
    },
    "/works/_projects/Zenzero": {
      "filePath": "works/_projects/Zenzero.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
